version: "3"

services:
  pb:
    build: pb
    ports:
      - 7071:8090
    volumes:
      - ./pb/pb_data:/usr/local/bin/pb_data
      - ./pb/pb_migrations:/usr/local/bin/pb_migrations
  web:
    build: ./frontend
    entrypoint: bun run build && bun run preview
    restart: always
    ports:
      - 7070:4173